<?php include ("../includes/header.php");?>
<?php include ("../includes/linkImports.php");?>
<script type="text/javascript">
	if (screen.width <= 800) {
  		window.location = "../ampcollections/UtahFifthDistrictBeaverCountyCaseIndexes.php";
	}
</script>
<!-- Mobile Links -->
<link rel="amphtml" href="../ampcollections/UtahFifthDistrictBeaverCountyCaseIndexes.php">
<link rel="alternate" media="only screen and (max-width: 640px)" href="../ampcollections/UtahFifthDistrictBeaverCountyCaseIndexes.php">
<!-- Collection #1266 -->
<!-- Collection Title -->
<title>Utah Fifth District: Beaver County Case Indexes</title>
<?php include("../includes/collectionmenuhead.php");?>
 
<!-- Share Links -->
<li class="mdl-menu__item"><a class="mdl-navigation__link"
                                  href="http://www.facebook.com/sharer/sharer.php?u=mwdl.org/collections/UtahFifthDistrictBeaverCountyCaseIndexes.php&t=Utah Fifth District: Beaver County Case Indexes"
                                  target="_blank"><img src="../images/facebook.png" alt="facebook"
                                                       height="20" width="20"> Facebook</a></li>
<li class="mdl-menu__item"><a class="mdl-navigation__link"
                                  href="http://www.twitter.com/intent/tweet?url=mwdl.org/collections/UtahFifthDistrictBeaverCountyCaseIndexes.php&via=@MountainWestDL&text=Utah Fifth District: Beaver County Case Indexes"
                                  target="_blank"><img src="../images/twitter.png" alt="twitter"
                                                       height="20" width="20"> Twitter</a></li>
<li class="mdl-menu__item"><a class="mdl-navigation__link"
                                  href="http://www.tumblr.com/share/link?url=mwdl.org/collections/UtahFifthDistrictBeaverCountyCaseIndexes.php"
                                  target="_blank"><img src="../images/tumblr.png"
                                                       alt="tumblr" height="20" width="20"> Tumblr</a></li>
</ul>
</div>
<div class="imageAndDes">
<!-- Image (if any)-->
<img src="../images/collection_images/collection1266.jpg" alt="The Copts and Christian Civilization"width="300" height="410"align= "right" style="max-width: 250px; height: auto; margin: 1%; display: block; ">
<!-- Image Description -->
The Copts and Christian Civilization
</div>
<!-- Collection Title-->
<h4>Utah Fifth District: Beaver County Case Indexes</h4>
<!-- Collection Publisher-->
<h6> Published by <a href="../partners/UtahStateArchives.php">Utah State Archives</a></h6>
 
<!-- Collection Description -->
</p><br/>This series is comprised of three index books kept by the Fifth District Court in Beaver County to access the civil and criminal case files generated by the court. Book 1 indexes by defendant surname between 1896 and 1950. Book 2 is a matching volume except that indexing is by plaintiff surname. Book 3 has sections organizing by both plaintiff and defendant surname between 1950 and 1998.</p><br/>&nbsp,</p><br/>
<hr>
<h6>
<!-- Browse Link -->
<a href="http://utah-primoprod.hosted.exlibrisgroup.com/primo_library/libweb/action/dlSearch.do?vid=MWDL&institution=MWDL&onCampus=false&search_scope=mw&query=lsr04,exact,1266&indx=1&bulkSize=50">Browse all record in Utah Fifth District: Beaver County Case Indexes</a>
</h6>
<p></p>
</div>
</div>
<?php include("../includes/footer.php"); ?>
