<?php include ("../includes/header.php");?>
<?php include ("../includes/linkImports.php");?>
<script type="text/javascript">
	if (screen.width <= 800) {
  		window.location = "../ampcollections/WorksProgressAdministrationBiographySketchesCollection.php";
	}
</script>
<!-- Mobile Links -->
<link rel="amphtml" href="../ampcollections/WorksProgressAdministrationBiographySketchesCollection.php">
<link rel="alternate" media="only screen and (max-width: 640px)" href="../ampcollections/WorksProgressAdministrationBiographySketchesCollection.php">
<!-- Collection #2306 -->
<!-- Collection Title -->
<title>Works Progress Administration Biography Sketches Collection</title>
<?php include("../includes/collectionmenuhead.php");?>
 
<!-- Share Links -->
<li class="mdl-menu__item"><a class="mdl-navigation__link"
                                  href="http://www.facebook.com/sharer/sharer.php?u=mwdl.org/collections/WorksProgressAdministrationBiographySketchesCollection.php&t=Works Progress Administration Biography Sketches Collection"
                                  target="_blank"><img src="../images/facebook.png" alt="facebook"
                                                       height="20" width="20"> Facebook</a></li>
<li class="mdl-menu__item"><a class="mdl-navigation__link"
                                  href="http://www.twitter.com/intent/tweet?url=mwdl.org/collections/WorksProgressAdministrationBiographySketchesCollection.php&via=@MountainWestDL&text=Works Progress Administration Biography Sketches Collection"
                                  target="_blank"><img src="../images/twitter.png" alt="twitter"
                                                       height="20" width="20"> Twitter</a></li>
<li class="mdl-menu__item"><a class="mdl-navigation__link"
                                  href="http://www.tumblr.com/share/link?url=mwdl.org/collections/WorksProgressAdministrationBiographySketchesCollection.php"
                                  target="_blank"><img src="../images/tumblr.png"
                                                       alt="tumblr" height="20" width="20"> Tumblr</a></li>
</ul>
</div>
<div class="imageAndDes">
<!-- Image (if any)-->
<img src="../images/collection_images/collection2306.jpg" alt="Emily Hodgetts Lowder" width="300" height ="250" align= "right" style="max-width: 250px; height: auto; margin: 1%; display: block; ">
<!-- Image Description -->
<a href="http://content.lib.utah.edu/cdm/ref/collection/ushs_wpabs/id/2148" target="_blank"><em>Emily Hodgetts Lowder</em></a>
</div>
<!-- Collection Title-->
<h4>Works Progress Administration Biography Sketches Collection</h4>
<!-- Collection Publisher-->
<h6> Published by <a href="../partners/DepartmentofHeritageandArts.php">Department of Heritage and Arts</a></h6>
 
<!-- Collection Description -->
</p>
 Short biographies generated by the Works Progress Administration from and about Utah's remaining pioneers and historical figures. The collection consists of Personal Pioneer History questionares, autobiographical and biographical sketches, autobiography and diary transcriptions. The items in this collection were generated by WPA field workers between 1936 and 1943.</p>

<hr>
<h6>
<!-- Browse Link -->

<a href=" http://utah-primoprod.hosted.exlibrisgroup.com/primo_library/libweb/action/search.do?tab=default_tab&mode=Advanced&scp.scps=scope:(mw)&vid=MWDL&indx=1&dum=true&srt=rank&frbg=&fn=search&ct=search&vl(1UI1)=exact&vl(35820410UI1)=lsr13&vl(freeText1)=Works+Progress+Administration+Biography+Sketches+Collection">Browse all records in Works Progress Administration Biography Sketches Collection</a></p>
</h6>
<p></p>
</div>
</div>
<?php include("../includes/footer.php"); ?>
