<?php include("../includes/ampheader.php");?>
<meta name="description" content="Utah Fifth District: Beaver County Case Indexes, a MWDL collection, presented by Utah State Archives">
<!-- Collection #1266 -->
<!-- Collection Title -->
<title>Utah Fifth District: Beaver County Case Indexes</title>
<!-- Desktop Version Link -->
<link rel="canonical" href="../collections/UtahFifthDistrictBeaverCountyCaseIndexes.php">
<?php include("../includes/ampstyle.php");?>
 
<!-- Collection Title -->
<h3>Utah Fifth District: Beaver County Case Indexes</h3>
<!-- Collection Publisher -->
<h6> Published by <a href="../partners/UtahStateArchives.php">Utah State Archives</a></h6>
<!-- Collection Image -->
<div class=amp-img-fill>
<amp-img src="../images/collection_images/collection1266.jpg"alt="The Copts and Christian Civilization"width="300" height ="410"  layout = "responsive"></amp-img>
</div>
<!-- Image Description -->
The Copts and Christian Civilization
<!-- Article Text -->
</p><br/>This series is comprised of three index books kept by the Fifth District Court in Beaver County to access the civil and criminal case files generated by the court. Book 1 indexes by defendant surname between 1896 and 1950. Book 2 is a matching volume except that indexing is by plaintiff surname. Book 3 has sections organizing by both plaintiff and defendant surname between 1950 and 1998.</p><br/>&nbsp
<hr>
<!-- Browse Collection -->
<h6>
<a href="http://utah-primoprod.hosted.exlibrisgroup.com/primo-explore/search?query=lsr04,exact1266&tab=default_tab&search_scope=mw&vid=MWDL&offset=0">Browse all record in Utah Fifth District: Beaver County Case Indexes</a>
</h6>
<?php include("../includes/ampfooter.php");?>
