<?php include("../includes/ampheader.php");?>
<!-- Collection #1266 -->
<!-- Collection Title -->
<title>Utah Fifth District: Beaver County Case Indexes</title>
<!-- Desktop Version Link -->
<link rel="canonical" href="../collections/UtahFifthDistrictBeaverCountyCaseIndexes.php">
<?php include("../includes/ampstyle.php");?>
 
<!-- Collection Title -->
<h3>Utah Fifth District: Beaver County Case Indexes</h3>
<!-- Collection Publisher -->
<h6> Published by <a href="../partners/UtahStateArchives.php">Utah State Archives</a></h6>
<!-- Collection Image -->
<div class=amp-img-fill>
<amp-img src="../images/collection_images/collection1266.jpg" alt="Plaintiff Index" width="300" height="410"> layout = "responsive"></amp-img>
</div>
<!-- Image Description -->
<a href="http://images.archives.utah.gov/cdm4/document.php?CISOROOT=/24549&CISOPTR=62&REC=1" target="_blank">Plaintiff Index 1896-1950<br> </a>
<!-- Article Text -->
</p>
This series is comprised of three index books kept by the Fifth District Court in Beaver County to access the civil and criminal case files generated by the court. Book 1 indexes by defendant surname between 1896 and 1950. Book 2 is a matching volume except that indexing is by plaintiff surname. Book 3 has sections organizing by both plaintiff and defendant surname between 1950 and 1998.</p>
&nbsp;</p>

<hr>
<!-- Browse Collection -->
<h6>

<a href=" http://utah-primoprod.hosted.exlibrisgroup.com/primo_library/libweb/action/search.do?tab=default_tab&mode=Advanced&scp.scps=scope:(mw)&vid=MWDL&indx=1&dum=true&srt=rank&frbg=&fn=search&ct=search&vl(1UI1)=exact&vl(35820410UI1)=lsr13&vl(freeText1)=Utah+Fifth+District:+Beaver+County+Case+Indexes">Browse all records in Utah Fifth District: Beaver County Case Indexes</a></p>
</h6>
<?php include("../includes/ampfooter.php");?>
