<?php include("../includes/ampheader.php");?>
<!-- Collection #2306 -->
<!-- Collection Title -->
<title>Works Progress Administration Biography Sketches Collection</title>
<!-- Desktop Version Link -->
<link rel="canonical" href="../collections/WorksProgressAdministrationBiographySketchesCollection.php">
<?php include("../includes/ampstyle.php");?>
 
<!-- Collection Title -->
<h3>Works Progress Administration Biography Sketches Collection</h3>
<!-- Collection Publisher -->
<h6> Published by <a href="../partners/DepartmentofHeritageandArts.php">Department of Heritage and Arts</a></h6>
<!-- Collection Image -->
<div class=amp-img-fill>
<amp-img src="../images/collection_images/collection2306.jpg" alt="Emily Hodgetts Lowder" width="300" height ="250" layout = "responsive"></amp-img>
</div>
<!-- Image Description -->
<a href="http://content.lib.utah.edu/cdm/ref/collection/ushs_wpabs/id/2148" target="_blank"><em>Emily Hodgetts Lowder</em></a>
<!-- Article Text -->
</p>
 Short biographies generated by the Works Progress Administration from and about Utah's remaining pioneers and historical figures. The collection consists of Personal Pioneer History questionares, autobiographical and biographical sketches, autobiography and diary transcriptions. The items in this collection were generated by WPA field workers between 1936 and 1943.</p>

<hr>
<!-- Browse Collection -->
<h6>

<a href=" http://utah-primoprod.hosted.exlibrisgroup.com/primo_library/libweb/action/search.do?tab=default_tab&mode=Advanced&scp.scps=scope:(mw)&vid=MWDL&indx=1&dum=true&srt=rank&frbg=&fn=search&ct=search&vl(1UI1)=exact&vl(35820410UI1)=lsr13&vl(freeText1)=Works+Progress+Administration+Biography+Sketches+Collection">Browse all records in Works Progress Administration Biography Sketches Collection</a></p>
</h6>
<?php include("../includes/ampfooter.php");?>
