<?php include("../includes/ampheader.php");?>
<meta name="description" content="Works Progress Administration Biography Sketches Collection, AMP">
<!-- Collection #2306 -->
<!-- Collection Title -->
<title>Works Progress Administration Biography Sketches Collection</title>
<!-- Desktop Version Link -->
<link rel="canonical" href="../collections/WorksProgressAdministrationBiographySketchesCollection.php">
<?php include("../includes/ampstyle.php");?>
 
<!-- Collection Title -->
<h3>Works Progress Administration Biography Sketches Collection</h3>
<!-- Collection Publisher -->
<h6> Published by <a href="../partners/DepartmentofHeritageandArts.php">Department of Heritage and Arts</a></h6>
<!-- Collection Image -->
<div class=amp-img-fill>
<amp-img src="../images/collection_images/collection2306.jpg"alt="fountain Hotel and Leather Pool"width="300" height ="250"  layout = "responsive"></amp-img>
</div>
<!-- Image Description -->
fountain Hotel and Leather Pool
<!-- Article Text -->
</p><br/> Short biographies generated by the Works Progress Administration from and about Utah's remaining pioneers and historical figures. The collection consists of Personal Pioneer History questionares, autobiographical and biographical sketches, autobiography and diary transcriptions. The items in this collection were generated by WPA field workers between 1936 and 1943.</p><br/>
<hr>
<!-- Browse Collection -->
<h6>
<a href="http://utah-primoprod.hosted.exlibrisgroup.com/primo_library/libweb/action/dlSearch.do?vid=MWDL&institution=MWDL&onCampus=false&search_scope=mw&query=lsr04,exact,2306&indx=1&bulkSize=50">Browse all record in Works Progress Administration Biography Sketches Collection</a>
</h6>
<?php include("../includes/ampfooter.php");?>
